### ISSUE TITLE
Skip over slicing

### ISSUE THREAD

**Issue by jamen** [juliangruber/balanced-match#12]
I'm creating a very lightweight module that can potentially run several millions of times per second.

Right now, I don't use this module because it slices the data automatically...  But I would like to use this module because of it's efficient balanced matching.

When you slice the data over and over millions of times when I don't need it, the nanosecond tasks start adding up into several hundreds of millisecond delays, and possibly even seconds. 

For my module, I am purely interested in the positions of the matches...  I can develop my own highly efficient slicing pattern specific to the data instead of this module doing it automatically when it is not what I need.

**Comment by juliangruber** [comment]
we can def. disable slicing via an option. mind making a pull request?

**Comment by neytema** [comment]
balanced.range(a, b, str)

**Comment by jamen** [comment]
Thank you, I had saw it in the source code, guess I did not see it exporting.

**Comment by juliangruber** [comment]
ha, thank you @neytema, knowing my module better than me :)

**Comment by juliangruber** [comment]
i guess this just shows that for a collaboratively improved open source module the initial author doesn't matter as much
