### ISSUE TITLE
bug!

### ISSUE THREAD

**Issue by janryWang** [juliangruber/balanced-match#21]
https://github.com/juliangruber/balanced-match/blob/master/index.js#L13
If a and b are null, then an error will be throw

**Comment by juliangruber** [comment]
oh, yeah you're right! do you want to create a pull request to fix this?

**Comment by gaythubtrash** [comment]
not fix,if a or b is null

**Comment by gaythubtrash** [comment]
> not fix,if a or b is null

'null'.indexOf(null) >0
