### ISSUE TITLE
No body when delimiters match

### ISSUE THREAD

**Issue by F1LT3R** [juliangruber/balanced-match#26]
I would expect matching delimiters to work. Ie: code fences in Markdown.

```markdown
    ```js
    const foo = bar => baz
    ```
```

It seems imposible to balance matching delimiters with `balanced-match`.

Is this expected?

Example:

```js
const balanced = require('balanced-match')

const contents = 'PRE ___BODY___ POST'
const result = balanced('___', '___', contents)

console.log(result)
```

Result:

(Where is the body?)

```js
{ start: 11, end: 11, pre: 'PRE ___BODY', body: '', post: ' POST' }
```

Expected:

(I was thinking we should see this)

```js
{ start: 4, end: 11, pre: 'PRE ', body: 'BODY', post: ' POST' }
```

**Comment by dimaio77** [comment]
this is a issue because a === b .
adding the following in line
if(a===b) {return [ai,bi]} in line 31 fix the problem

**Comment by juliangruber** [comment]
Thank you for reporting and investigating this, would you mind opening a PR with your fix, and even better, with some tests too?
