### ISSUE TITLE
Error with new version launched today

### ISSUE THREAD

**Issue by pimfeltkamp** [juliangruber/balanced-match#31]
Hi,

Since the launch of the new version today I get the following error:

/node_modules/balanced-match/index.js:7 const r = range(a, b, str) ^^^^^ 
SyntaxError: Use of const in strict mode. 

What do I need to do?

Kind Regards

**Comment by alexandrubirlan** [comment]
+1

**Comment by alexandrubirlan** [comment]
if this works with a different version of ES, it should be specified somewhere

**Comment by pimfeltkamp** [comment]
I think this should have been an update to 2.0.0 instead of 1.0.1

**Comment by alexandrubirlan** [comment]
would make sense since this looks like a breaking change

**Comment by juliangruber** [comment]
I'm sorry about this, will fix asap

**Comment by pimfeltkamp** [comment]
Thanks! Excellent and fast service! 💯

**Comment by juliangruber** [comment]
I forgot that people might be using this with node versions that don't support `const`

**Comment by juliangruber** [comment]
https://github.com/juliangruber/balanced-match/releases/tag/v1.0.2

**Comment by juliangruber** [comment]
https://github.com/juliangruber/balanced-match/releases/tag/v2.0.0
